### ISSUE TITLE
Fix pushrelease Actions in qTrade package

### ISSUE THREAD

**Issue by BBieri** [globalgov/manytrade#13]
PushRelease actions are not working as of now. Make them run!

**Comment by henriquesposito** [comment]
We have the same issue for qCreate now and, I believe, we will have the same issue for all other qPackages once we merge branches. The issue is with cURL authorizations, I think. GitHub has gotten stricter about personal access tokens (PAT) for accessing/downloading from all private repos lately. I think we will have to add a "secret" identification key at the organization level to avoid this error. This should not be an issue though once qData is available on CRAN.  

There are two solutions, as I see it.  We remove the readme rendering portion of the push release workflow actions (for now) and add rendering the readme.md as a item in the checklist for the PR templates. Or, we create and add the PAT to the push rreleaseworkflow file and template.

**Comment by henriquesposito** [comment]
Another solution is to set eval = FALSE on the README.Rmd chunck in qPackages that rely on qData, so that the README does not need qData to render for now. This would allow us to keep the rendering of the README in the push release workflow, but without having to download/install qData which is causing the issue.
